name: testproject
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.5
  auto_size_text: ^3.0.0
  freezed_annotation: ^2.4.4
  injectable: ^2.4.2
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  rx_shared_preferences: ^4.0.0
  auto_route: ^9.2.2
  flutter_native_splash: ^2.4.1
  flutter_dotenv: ^5.1.0
  result_dart: ^2.0.0
  json_annotation: ^4.9.0
  pretty_animated_buttons: ^0.0.2
  flutter_staggered_grid_view: ^0.7.0
  smooth_page_indicator: ^1.1.0
  firebase_core: ^3.12.0
  firebase_analytics: ^11.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.0
  freezed: ^2.5.2
  injectable_generator: ^2.4.2
  flutter_gen_runner: ^5.4.0
  intl_utils: ^2.8.7
  auto_route_generator: ^9.0.0
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.2
  flutter_launcher_icons: "^0.14.3"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
      
flutter_intl:
  enabled: true
  main_locale: "en"
  arb_dir: assets/l10n

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.jpg"
  min_sdk_android: 21 