// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNUry_bPSiYrrPMQSsCTD96hs9TjH-icw',
    appId: '1:711570160354:web:dde3826f3a752525f53cbb',
    messagingSenderId: '711570160354',
    projectId: 'project1-test-5a63b',
    authDomain: 'project1-test-5a63b.firebaseapp.com',
    storageBucket: 'project1-test-5a63b.firebasestorage.app',
    measurementId: 'G-2MH8ZRPQTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVqEF6zHoopVVK667EemZff27hvlgVRF0',
    appId: '1:711570160354:android:803b70df8cb087a1f53cbb',
    messagingSenderId: '711570160354',
    projectId: 'project1-test-5a63b',
    storageBucket: 'project1-test-5a63b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASJM0M8IVpe3gfwQsULrX7skfOTlg_fCM',
    appId: '1:711570160354:ios:13c4c059ca3c8525f53cbb',
    messagingSenderId: '711570160354',
    projectId: 'project1-test-5a63b',
    storageBucket: 'project1-test-5a63b.firebasestorage.app',
    iosBundleId: 'com.example.testproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASJM0M8IVpe3gfwQsULrX7skfOTlg_fCM',
    appId: '1:711570160354:ios:13c4c059ca3c8525f53cbb',
    messagingSenderId: '711570160354',
    projectId: 'project1-test-5a63b',
    storageBucket: 'project1-test-5a63b.firebasestorage.app',
    iosBundleId: 'com.example.testproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNUry_bPSiYrrPMQSsCTD96hs9TjH-icw',
    appId: '1:711570160354:web:bac30578131bfc15f53cbb',
    messagingSenderId: '711570160354',
    projectId: 'project1-test-5a63b',
    authDomain: 'project1-test-5a63b.firebaseapp.com',
    storageBucket: 'project1-test-5a63b.firebasestorage.app',
    measurementId: 'G-9RK7Y7J0CF',
  );
}
